# Generated by Django 2.0 on 2017-12-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_data', '0002_auto_20171217_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('year', models.CharField(max_length=4)),
                ('game_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('game_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('team', models.CharField(max_length=3)),
                ('game_location', models.CharField(max_length=30)),
                ('opponent', models.CharField(max_length=3)),
                ('game_won', models.BooleanField()),
                ('player_team_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('passing_attempts', models.IntegerField()),
                ('passing_completions', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('passing_rating', models.IntegerField()),
                ('passing_touchdowns', models.IntegerField()),
                ('passing_interceptions', models.IntegerField()),
                ('passing_sacks', models.IntegerField()),
                ('passing_sacks_yards_lost', models.IntegerField()),
                ('rushing_attempts', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('rushing_touchdowns', models.IntegerField()),
                ('receiving_targets', models.IntegerField()),
                ('reveiving_receptions', models.IntegerField()),
                ('reveiving_yards', models.IntegerField()),
                ('receiving_touchdowns', models.IntegerField()),
                ('kick_return_attempts', models.IntegerField()),
                ('kick_return_yards', models.IntegerField()),
                ('kick_return_tocuhdowns', models.IntegerField()),
                ('punt_return_attempts', models.IntegerField()),
                ('punt_return_yards', models.IntegerField()),
                ('punt_return_touchdowns', models.IntegerField()),
                ('defense_sacks', models.IntegerField()),
                ('defense_tackles', models.IntegerField()),
                ('defense_tackle_assists', models.IntegerField()),
                ('defense_interceptions', models.IntegerField()),
                ('defense_interception_yards', models.IntegerField()),
                ('defense_interception_touchdowns', models.IntegerField()),
                ('defense_safeties', models.IntegerField()),
                ('point_after_attemps', models.IntegerField()),
                ('point_after_makes', models.IntegerField()),
                ('field_goal_attempts', models.IntegerField()),
                ('field_goal_makes', models.IntegerField()),
                ('punting_attempts', models.IntegerField()),
                ('punting_yards', models.IntegerField()),
                ('punting_blocked', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_data.Profile')),
            ],
        ),
    ]
