# Generated by Django 2.0 on 2017-12-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_data', '0004_auto_20171217_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.CharField(max_length=6),
        ),
    ]
