# Generated by Django 2.0 on 2017-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_data', '0006_auto_20171217_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_salary',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
